django_project_login_Password_reset-main/accounts/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

django_project_login_Password_reset-main/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

django_project_login_Password_reset-main/accounts/models.py
from django.db import models

# Create your models here.

django_project_login_Password_reset-main/accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
import render


def SignUpView(request):
    return render(request, 'registeration/login.html')

django_project_login_Password_reset-main/accounts/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}Django Auth and Polls{% endblock %}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}" />
  </head>
  <body>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

django_project_login_Password_reset-main/accounts/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'polls:index' %}">Polls</a></p>
  <p><a href="{% url 'logout' %}">Log Out</a></p>
  <p><a href="{% url 'password_reset' %}">Reset Password</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
  <br>
  <br>
  <a href="{% url 'signup' %}">Create a New Account</a>
{% endif %}
{% endblock %}